### ISSUE TITLE
[BUG] BP needed to destroy turfs does not correspond to their current health value

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#171] opened 2021-09-02 12:30 UTC
**Describe the bug**
You can destroy roofs without even getting near the BP (aka Health) it has. A roof with 350k BP can be destructed with as little as 20k BP. I've tried and you can even destroy a 3.5m BP roof without a problem. With 20k BP. 

A 35m BP roof can't be destruct with 20k BP, however. But it can be destroyed with 24k BP. I'm not really sure what is happening, since all turf configs were on default. I've tried changing all vars related to turfs several times to see if it was something configured wrong but in the end it didn't even matter.

That said, it *could* be some wrong config but since I don't really know what they do *exactly* other than what can be inferred for their name, I can't do anything.

From what I noticed, the actual BP needed to destroy the turf is about its current health value divided by around 1330 or so.

My character with 20600 BP can't destroy a 32'165'610 BP roof, but if I power up to about 23800 it will be destroyed by a a single punch. 

Doors also follow that line of thinking, and Walls could always be destroyed like that from what I can remember (but who cares about cannon fodder like walls?).

**To Reproduce**
1, Create a roof or a door and upgrade it to above your current BP value.
2. Punch it.
3. See that the constructed turf does not exist anymore.

**Expected behavior**
Roof BP should be the current BP needed to destroy it (modified by anything that changes that value). 

**Screenshots**
Roof with 30m Health getting destroyed by a 23k BP character:
https://user-images.githubusercontent.com/81521485/131842597-fcabf07a-a4f6-4405-94bb-cdd0aadf5568.mp4

**Byond Details:**
N/A.

**First identifiable version:**
Dragon Universe Classic 35.6.5.

**Comment by Khunkurisu** [comment] 2021-09-04 21:44
Because it's checking how much damage you deal in X time, not how much BP you have.  Turfs have no defensive stats, causing it to scale damage much much higher than you'd expect.  This is more an issue of a poorly designed building/map destruction system, rather than a bug.  Since technically it's working as intended.

**Comment by Kaseioo** [comment] 2021-09-05 16:35
Well, I reported it as a bug since it wasn't like that on other versions (it wasn't, right? If it was, curse you, brain). I thought it had something to do with this update. Should I close this Issue? 

I DID notice that when I didn't destroy it, its health would go down by a small amount (around ten or so health). Are walls supposed to be destroyed only with beams?

**Comment by Khunkurisu** [comment] 2021-09-06 08:52
I'm leaving the issue open as a reminder to look into improving/changing the mechanics for how base destruction works.  You may close it if you wish to make a suggestion on that topic instead.  To answer your question, it certainly worked the same way prior.  The only changes I've made are to melee damage specifically, which likely increased the chances of you breaking the wall with a non-ki attack.

**Comment by Khunkurisu** [comment] 2021-10-03 08:30
I have redone the scaling of this.  Some tweaking needs to be done to make it so that walls actually scale properly without any config edits (there are configs that fix this under 'General Mechanics'), but you can now only break walls if you can reach a BP roughly within 10% of its Health value.  The new "BP Tiers" add a 10% bonus to wall damage per level, as well.  This should make bases an actual possibility again!

**Closed as completed by Khunkurisu** 2021-10-03 08:30 UTC
Labels: bug
