### ISSUE TITLE
[BUG] Eating a Power Fruit makes the game freeze for a few seconds

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#105] opened 2021-04-02 02:17 UTC
**Describe the bug**
See title. Whenever a Power Fruit (from the 'make Power Fruit' skill) is eaten, the *entire* game freezes for a few seconds.

**To Reproduce**
1. Use the Make Power Fruit skill
2. Eat the fruit
3. See the game freeze for a few seconds.

**Expected behavior**
The game should not freeze whenever a power fruit is eaten.

**Screenshots**
N/A.

**Byond Details:**
The BYOND version of the host was 513.1542.

First identifiable version:
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304".

**Comment by Khunkurisu** [comment] 2021-04-02 16:48
See my comment on #104.

**Comment by Khunkurisu** [comment] 2021-04-02 18:33
Possibly fixed.  Will leave open for the time being, but fingers crossed the issue is resolved.

**Comment by Khunkurisu** [comment] 2021-04-12 13:39
This is confirmed fixed in next update, at least on any server I was able to use for testing- even one of poor quality.

**Closed as completed by Khunkurisu** 2021-04-12 13:39 UTC
Labels: bug
