### ISSUE TITLE
[BUG] When a Splitform is killed, the entire game stops responding for a few seconds

### ISSUE THREAD

**Issue by Kaseioo** [DU-Devs/Dragon-Universe-Public#104] opened 2021-04-02 02:08 UTC
**Describe the bug**
See title. Whenever a Splitform is killed, the game freezes/lags/stops responding for a few seconds.

**To Reproduce**
1. Create a splitform
2. Kill it
3. See the game freeze for a few seconds.

**Expected behavior**
The game should not freeze when a splitform is killed.

**Screenshots**
N/A.

**Byond Details:**
The BYOND version of server was 513.1542.

**First identifiable version:**
The version the bug was detected was the March 4th, 2021 (2021-03-04) release, named "Dragon Universe Classic r20210304".

**Comment by Khunkurisu** [comment] 2021-04-02 16:47
There are several posts here now about the game freezing/locking up when performing certain actions.  However, I've never encountered this many hangs in the game.  It seems from some of your descriptions you're playing on a server when testing this- have you tried testing on another server or in a singleplayer game?  It's entirely possible the server you're using is the issue.

**Comment by Khunkurisu** [comment] 2021-04-02 18:39
This is most likely fixed in the upcoming patch.  Leaving open since I have no way of testing since I could not reproduce the issue.

**Comment by Khunkurisu** [comment] 2021-04-12 13:39
This is confirmed fixed in next update, at least on any server I was able to use for testing- even one of poor quality.

**Closed as completed by Khunkurisu** 2021-04-12 13:39 UTC
Labels: bug, clarity needed
